# Generated by Django 5.0.4 on 2024-05-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_child_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='father',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='GrandParent',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
