# Generated by Django 5.0.4 on 2024-05-10 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.IntegerField(default=2100000000, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number is invalid', regex='^(?!0)\\d{10}$')]),
            preserve_default=False,
        ),
    ]
