# Generated by Django 5.0.4 on 2024-05-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_answer_category_question_quizzes_delete_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
