# Generated by Django 5.0.4 on 2024-05-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.grandparent')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.grandparent')),
            ],
        ),
    ]
